# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mfp < Formula
  desc "Terminal UI for musicforprogramming.net — streams all MFP episodes in your terminal"
  homepage "https://github.com/fpigeonjr/music-for-coding-tui"
  version "0.2.0"
  license "MIT"

  depends_on "mpv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_darwin_amd64.tar.gz"
      sha256 "e0e7de51f65413615c1f74355cae68252fe9cde4de3423525d6c51bf4677005d"

      define_method(:install) do
        bin.install "mfp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_darwin_arm64.tar.gz"
      sha256 "eebec61ab55017d0eae2dc8d6df78ec1dff5f3b63d7dc4e820b9ea4cc9ccebe2"

      define_method(:install) do
        bin.install "mfp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_linux_amd64.tar.gz"
      sha256 "65c212084a38004e29f7b294242b671e3906e255ec24994ac5983404120f9ace"
      define_method(:install) do
        bin.install "mfp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_linux_arm64.tar.gz"
      sha256 "0c2b7c118b4ba9284a0a0e84df03e7c165dc040ad9da274f8e5f21eaff06e317"
      define_method(:install) do
        bin.install "mfp"
      end
    end
  end

  test do
    system "#{bin}/mfp --version"
  end
end
