# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mfp < Formula
  desc "Terminal UI for musicforprogramming.net — streams all MFP episodes in your terminal"
  homepage "https://github.com/fpigeonjr/music-for-coding-tui"
  version "0.2.0"
  license "MIT"

  depends_on "mpv"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_darwin_amd64.tar.gz"
      sha256 "d3c549158041aadb1fd07666c8de06d2f44fff146151f1512313df54391524ee"

      define_method(:install) do
        bin.install "mfp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_darwin_arm64.tar.gz"
      sha256 "44fc239b64909ddb999ce9e72c697715cddfbac020e651e3755977841ee2c4a5"

      define_method(:install) do
        bin.install "mfp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_linux_amd64.tar.gz"
      sha256 "0e6b63a5b8916cc8699be2f2dc09b5f38aa944ab9537f3bfaf356887f8169009"
      define_method(:install) do
        bin.install "mfp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fpigeonjr/music-for-coding-tui/releases/download/v0.2.0/mfp_0.2.0_linux_arm64.tar.gz"
      sha256 "77b1451bb2425ff5dbec93760ef99fc40411a4aa1f59246983cd787af53b8c46"
      define_method(:install) do
        bin.install "mfp"
      end
    end
  end

  test do
    system "#{bin}/mfp --version"
  end
end
